_config.yml, index.md
=> Change readme

Karaoke.2020.0426.md, index.md
1. add first change log.
2. add some role in readme.
=> Add initial log

Developer.md, changelog/2020.0501/README.md
Add 2020.0501 change log
Also testing :
- gif display in lazer.
- relative link.
=> Add 2020.0501 change log

.gitignore, .vscode/launch.json, Developer.md, Gemfile, _config.yml, changelog/2020.0401/README.md, changelog/2020.0412/README.md, changelog/2020.0426/README.md, changelog/2020.0501/README.md, changelog/2020.0508/README.md, changelog/README.md, index.md
=> Change theme

changelog/2020.0515/README.md, changelog/2020.0522/README.md
Add change log
Will be change into 2020.0508 if progress is enough.
=> Add 2020.0515 change log

index.md
=> Add introduce page at index.

changelog/2020.0606/README.md
=> add 2020.0606 changelog

_layouts/changelog.html, changelog/2020.0704/README.md
=> Fix tag typing error.

index.md
=> translation fixes

Developer.md, changelog/2020.0508/README.md, changelog/2020.1024/README.md, changelog/2020.1128/README.md
Fix pull request's tag position.
=> Fix pull request's tag position.

changelog/2021.0109/README.md, changelog/2021.0123/README.md
=> Update those stupid progress.

changelog/2021.0208/README.md
=> Add new changelog.

changelog/2021.0417/README.md
=> Add latest readmd.

Developer.md, content/changelog/2020.0606/index.md, content/changelog/2021.0918/index.md, layouts/partials/script/github-mention-link.html
What's added in this PR:
- Add changelog
- Add more repo tags.
=> Add new changelog

.github/PULL_REQUEST_TEMPLATE/create-changelog.md
=> Create pull-request template.

content/changelog/2021.1212/index.md, content/changelog/2022.0101/index.md
Create new changelog 2022.0101
=> Changelog 2022.0101

content/changelog/2022.0212/index.md
https://github.com/karaoke-dev/karaoke/milestone/32
Create new changelog 2022.0212
=> Changelog 2022.0212

Developer.md, content/changelog/2022.0716/index.md
https://github.com/karaoke-dev/karaoke/milestone/39
Create new changelog 2022.0716
=> Changelog 2022.0716

.github/workflows/gh-pages.yml
Here's the complain:
https://github.com/karaoke-dev/karaoke-dev.github.io/actions/runs/4608023335?pr=77
Here's the explain:
https://github.com/actions/runner-images/issues/6002
=> Upgrade the ubuntu version to the latest.

content/changelog/2023.0606/index.md
https://github.com/karaoke-dev/karaoke/milestone/51
Create new changelog 2023.0606
=> Changelog 2023.0606

.editorconfig, .gitattributes, .gitignore
=> Sync file config from the osu-wiki

.github/workflows/prettier.yml
=> Add github action to check if the markdown file is formatted.

content/changelog/2023.0806/index.md
https://github.com/karaoke-dev/karaoke/milestone/53
Create new changelog 2023.0806
=> Changelog 2023.0806

content/changelog/2023.1111/index.md
https://github.com/karaoke-dev/karaoke/milestone/56
Create new changelog 2023.1111
=> Changelog 2023.1111

content/changelog/2023.1212/index.md
https://github.com/karaoke-dev/karaoke/milestone/57
Create new changelog 2023.1212
=> Changelog 2023.1212
